### ISSUE TITLE
command line options don't work?

### ISSUE THREAD

**Issue by FlatEarthDave** [Zeranoe/mingw-w64-build#14]
The scrypt seems to just ignore command line [options]. I tried to set the gcc version, but thought I must be doing something wrong, so I ended up downloading the version I wanted, put it in the pkgs folder, and changed the name, so the scrypt would skip extracting it. I tried <code>python3 tc-builder.py --skip-gmp --skip-mpfr --skip-isl --skip-mpc </code>, but it configures and builds each one still. It doesn't just say that it's building them, it must be, because of the time it spends on each option. I just wanted to bring it to your attention - someone with a slow cpu, and not very many cores, could spend a lot of unnecessary time on those steps. Maybe I'm doing something wrong. Thanks.

Also, why will it not download the latest gcc? it only wants to get 9.3.0, but 10.1.0 is available on the same server.

**Comment by FlatEarthDave** [comment]
I guess I should add, that pretty much all the dependencies are outdated. 

<code>Downloaded from HTTP                                                                                                    {'gmp': './pkgs/gmp-6.1.0', 'isl': './pkgs/isl-0.18', 'mingw-w64': './pkgs/mingw-w64-7.0.0', 'pkgconf': './pkgs/pkgconf-1.6.3', 'gcc': './pkgs/gcc-9.3.0', 'mpc': './pkgs/mpc-1.0.3', 'binutils': './pkgs/binutils-2.34', 'mpfr': './pkgs/mpfr', 'cloog': './pkgs/cloog-0.18.1'} </code>

gmp-6.2.0, isl-0.21, gcc-10.1.0, mpc-1.1.0 are more recent versions, they had to be downloaded and put in pkgs folder to trick the scrypt.

**Comment by Zeranoe** [comment]
The gmp version has been addressed in 0e8f42bc93da84c1279128951b54f9874ce8d555.

I'm going to hold off on updating GCC to 10 until it's a bit more mature.

I'm not sure what you mean by the command line arguments, but those aren't listed in `--help`.

**Comment by FlatEarthDave** [comment]
I'll remove this. It was meant for another person's script.
