### ISSUE TITLE
Error error: missing ARCH option when using the script.

### ISSUE THREAD

**Issue by hnguyen48206** [Zeranoe/mingw-w64-build#21]
Hi sir,

I'm trying to follow this tutorial: https://kimathir.wordpress.com/2016/10/12/cross-compile-ffmpeg-for-windows-ubuntu-16-04/ to cross-compile ffmpeg on linux. When I run your script with the command  "bash ./mingw-w64-build", I have encountered this message below which I have no clue how to get it work.

Any help would be reaaly appriciated.

![image](https://user-images.githubusercontent.com/28868992/128124871-9cca224d-6351-4c60-bcc1-af6dab3b7d09.png)

**Comment by Zeranoe** [comment]
You'll need to provide the script an architecture/target, which are i686 (Windows 32-bit) or x86_64 (Windows 64-bit).

To build a toolchain for Windows 64-bit, you would run `bash ./mingw-w64-build x86_64`
