### ISSUE TITLE
Compiling gdbserver - Need help 

### ISSUE THREAD

**Issue by clauderobi** [Zeranoe/mingw-w64-build#25]
Hi, I am trying to modify the script to compile gdbserver. (And gdb, which I was successful at doing). 

I added this after gcc is compiled;
`   create_dir "$bld_path/binutils/gdbserver"
    change_dir "$bld_path/binutils/gdbserver"

    execute "($arch): configuring gdbserver" "" \
        "$SRC_PATH/binutils/gdbserver/configure" --prefix="$prefix" --disable-nls --host="$host" 

    execute "($arch): building gdbserver" "" \
        make -j $JOB_COUNT

    execute "($arch): installing gdbserver" "" \
        make install`
But I get this `fatal error: langinfo.h: No such file or directory` when building.
(The disable-nls did not make a change even after I added it)

In the log I see this:
`checking for x86_64-w64-mingw32-gcc...` so I see that the correct compiler is being picked up.

I Googled a bit to see how gdbserver should be configured and beside the host apparently nothing should be needed. So I am not sure what I am doing wrong.

**Comment by Zeranoe** [comment]
As described [in the README for gdbserver](https://sourceware.org/git/?p=binutils-gdb.git;a=blob;f=gdbserver/README) you want to add `--disable-gdb` to configure. Then it's simply `make all-gdbserver`.

Closing as off-topic
