### ISSUE TITLE
Are you still develop it?

### ISSUE THREAD

**Issue by 3oheicrw** [Zeranoe/mingw-w64-build#28]
Please update to MinGW-w64 10.0.0

**Comment by 3oheicrw** [comment]
It seems he's no longer developed it.

**Comment by utoni** [comment]
Please give @zeranoe some time to answer your question.

**Comment by ppigazzini** [comment]
> Please update to MinGW-w64 10.0.0

Check here the names of mingw-w64 tags/branches:
 - tags:
https://sourceforge.net/p/mingw-w64/mingw-w64/ref/master/tags/
 - branches:
https://sourceforge.net/p/mingw-w64/mingw-w64/ref/master/branches/

Set yourself the desired mingw-w64 tag/branch, at example here is the "v10.0.0" tag:
```bash
./mingw-w64-build x86_64 --mingw-w64-branch "v10.0.0"
```
