### ISSUE TITLE
Fix SRC_PATH setting when using CACHED_SOURCES

### ISSUE THREAD

**Issue by tokomine** [Zeranoe/mingw-w64-build#34]
I found a bug in the mingw-w64-build script that prevents it from setting the SRC_PATH variable correctly when using the CACHED_SOURCES option.

I have submitted a pull request with this fix. Please review and merge it if you agree with my solution. Thank you.

https://github.com/Zeranoe/mingw-w64-build/pull/33

**Comment by Zeranoe** [comment]
Merged, thank you!
