### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by GooglePlugin** [Zeranoe/mingw-w64-build#4]
When I am using  this build-script, It failed because of binutils.
Here is the build.log.
`Initialized empty Git repository in /workspace/build/mingw-w64-build-master/src/mingw-w64-git/.git/
2018-01-30 08:41:34 URL:http://ftp.gnu.org/gnu/binutils/binutils-2.29.1.tar.bz2 [29123355/29123355] -> "binutils-2.29.1.tar.bz2" [1]
2018-01-30 08:42:23 URL:http://ftp.gnu.org/gnu/gcc/gcc-7.2.0/gcc-7.2.0.tar.xz [62312628/62312628] -> "gcc-7.2.0.tar.xz" [1]
2018-01-30 08:42:41 URL:http://ftp.gnu.org/gnu/gmp/gmp-6.1.2.tar.xz [1946336/1946336] -> "gmp-6.1.2.tar.xz" [1]
2018-01-30 08:42:45 URL:http://ftp.gnu.org/gnu/mpfr/mpfr-3.1.6.tar.xz [1133672/1133672] -> "mpfr-3.1.6.tar.xz" [1]
2018-01-30 08:42:48 URL:http://ftp.gnu.org/gnu/mpc/mpc-1.0.3.tar.gz [669925/669925] -> "mpc-1.0.3.tar.gz" [1]
patching file libstdc++-v3/config/os/mingw32-w64/os_defines.h
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-w64-mingw32
checking for a BSD-compatible install... /usr/bin/install -c
checking whether ln works... yes
checking whether ln -s works... yes
checking for a sed that does not truncate output... /bin/sed
checking for gawk... gawk
checking for gcc... gcc
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables... 
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... unsupported
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking whether g++ accepts -static-libstdc++ -static-libgcc... yes
checking for gnatbind... no
checking for gnatmake... no
checking whether compiler driver understands Ada... no
checking how to compare bootstrapped objects... cmp --ignore-initial=16 $$f1 $$f2
checking for objdir... .libs
checking for isl 0.16, 0.15, or deprecated 0.14... no
recommended isl version is 0.16 or 0.15, the minimum required isl version 0.14 is deprecated
checking for isl 0.16 or 0.15... no
checking for default BUILD_CONFIG... 
checking for --enable-vtable-verify... no
checking for bison... bison -y
checking for bison... bison
checking for gm4... no
checking for gnum4... no
checking for m4... m4
checking for flex... flex
checking for flex... flex
checking for makeinfo... no
/workspace/build/mingw-w64-build-master/src/binutils-2.29.1/missing: line 81: makeinfo: command not found
checking for expect... expect
checking for runtest... no
checking for ar... ar
checking for as... as
checking for dlltool... no
checking for ld... ld
checking for lipo... no
checking for nm... nm
checking for ranlib... ranlib
checking for strip... strip
checking for windres... no
checking for windmc... no
checking for objcopy... objcopy
checking for objdump... objdump
checking for readelf... readelf
checking for x86_64-w64-mingw32-cc... no
checking for x86_64-w64-mingw32-gcc... no
checking for x86_64-w64-mingw32-c++... no
checking for x86_64-w64-mingw32-g++... no
checking for x86_64-w64-mingw32-cxx... no
checking for x86_64-w64-mingw32-gxx... no
checking for x86_64-w64-mingw32-gcc... no
checking for x86_64-w64-mingw32-gfortran... no
checking for x86_64-w64-mingw32-gccgo... no
checking for x86_64-w64-mingw32-ar... no
checking for x86_64-w64-mingw32-as... no
checking for x86_64-w64-mingw32-dlltool... no
checking for x86_64-w64-mingw32-ld... no
checking for x86_64-w64-mingw32-lipo... no
checking for x86_64-w64-mingw32-nm... no
checking for x86_64-w64-mingw32-objcopy... no
checking for x86_64-w64-mingw32-objdump... no
checking for x86_64-w64-mingw32-ranlib... no
checking for x86_64-w64-mingw32-readelf... no
checking for x86_64-w64-mingw32-strip... no
checking for x86_64-w64-mingw32-windres... no
checking for x86_64-w64-mingw32-windmc... no
checking where to find the target ar... just compiled
checking where to find the target as... just compiled
checking where to find the target cc... pre-installed
checking where to find the target c++... pre-installed
checking where to find the target c++ for libstdc++... pre-installed
checking where to find the target dlltool... just compiled
checking where to find the target gcc... pre-installed
checking where to find the target gfortran... pre-installed
checking where to find the target gccgo... pre-installed
checking where to find the target ld... just compiled
checking where to find the target lipo... pre-installed
checking where to find the target nm... just compiled
checking where to find the target objcopy... just compiled
checking where to find the target objdump... just compiled
checking where to find the target ranlib... just compiled
checking where to find the target readelf... just compiled
checking where to find the target strip... just compiled
checking where to find the target windres... just compiled
checking where to find the target windmc... just compiled
checking whether to enable maintainer-specific portions of Makefiles... no
configure: creating ./config.status
config.status: creating Makefile
make[1]: Entering directory `/workspace/build/mingw-w64-build-master/bld/binutils'
make[1]: Nothing to be done for `all-target'.
mkdir -p -- ./intl
mkdir -p -- ./zlib
mkdir -p -- ./libiberty
mkdir -p -- ./etc
Configuring in ./intl
Configuring in ./zlib
Configuring in ./libiberty
Configuring in ./etc
configure: creating cache ./config.cache
configure: creating cache ./config.cache
configure: creating cache ./config.cache
checking for a BSD-compatible install... configure: creating cache ./config.cache
/usr/bin/install -c
checking whether to enable maintainer-specific portions of Makefiles... no
checking for makeinfo... /workspace/build/mingw-w64-build-master/src/binutils-2.29.1/missing makeinfo --split-size=5000000
checking whether make sets $(MAKE)... configure: WARNING:
*** Makeinfo is missing. Info documentation will not be built.
checking for perl... perl
yes
checking for a BSD-compatible install... /usr/bin/install -c
checking whether NLS is requested... no
checking build system type... checking build system type... checking for msgfmt... configure: updating cache ./config.cache
x86_64-pc-linux-gnu
checking host system type... configure: creating ./config.status
x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
checking for x86_64-pc-linux-gnu-ar... ar
checking for x86_64-pc-linux-gnu-ranlib... ranlib
checking whether to install libiberty headers and static library... no
configure: target_header_dir = 
checking for x86_64-pc-linux-gnu-gcc... gcc
/usr/bin/msgfmt
checking for gmsgfmt... /usr/bin/msgfmt
checking for xgettext... x86_64-w64-mingw32
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... /usr/bin/xgettext
checking for msgmerge... /usr/bin/msgmerge
checking for x86_64-pc-linux-gnu-gcc... gcc
checking for C compiler default output file name... checking for C compiler default output file name... config.status: creating Makefile
a.out
checking whether the C compiler works... a.out
checking whether the C compiler works... yes
yes
checking whether we are cross compiling... no
checking for suffix of executables... checking whether we are cross compiling... no
checking for suffix of executables... 

checking for suffix of object files... checking for suffix of object files... make[2]: Entering directory `/workspace/build/mingw-w64-build-master/bld/binutils/etc'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/workspace/build/mingw-w64-build-master/bld/binutils/etc'
o
o
checking whether we are using the GNU C compiler... checking whether we are using the GNU C compiler... yes
yes
checking whether gcc accepts -g... checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... yes
checking for gcc option to accept ISO C89... unsupported
unsupported
checking how to run the C preprocessor... checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for x86_64-pc-linux-gnu-ranlib... ranlib
checking for library containing strerror... none required
checking how to run the C preprocessor... /lib/cpp
configure: error: in `/workspace/build/mingw-w64-build-master/bld/binutils/libiberty':
configure: error: C preprocessor "/lib/cpp" fails sanity check
See `config.log' for more details.
make[1]: *** [configure-libiberty] Error 1
make[1]: *** Waiting for unfinished jobs....
/lib/cpp
configure: error: in `/workspace/build/mingw-w64-build-master/bld/binutils/intl':
configure: error: C preprocessor "/lib/cpp" fails sanity check
See `config.log' for more details.
make[1]: *** [configure-intl] Error 1
yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking for x86_64-pc-linux-gnu-gcc... gcc
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables... 
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... unsupported
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... ld
checking if the linker (ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... nm
checking the name lister (nm) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1966080
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking for ld option to reload object files... -r
checking for x86_64-pc-linux-gnu-objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for x86_64-pc-linux-gnu-ar... ar
checking for x86_64-pc-linux-gnu-strip... no
checking for strip... strip
checking for x86_64-pc-linux-gnu-ranlib... ranlib
checking command to parse nm output from gcc object... ok
checking how to run the C preprocessor... /lib/cpp
configure: error: in `/workspace/build/mingw-w64-build-master/bld/binutils/zlib':
configure: error: C preprocessor "/lib/cpp" fails sanity check
See `config.log' for more details.
make[1]: *** [configure-zlib] Error 1
make[1]: Leaving directory `/workspace/build/mingw-w64-build-master/bld/binutils'
make: *** [all] Error 2`
Cloud you help me?

**Comment by Zeranoe** [comment]
What are you trying to build from?

**Comment by Zeranoe** [comment]
No response and I suspect this was being attempted from something like MSYS which is not supported.
