### ISSUE TITLE
Move to gcc 7.4 to have the mitigation for upstream gcc bug on macOS 10.13 APFS

### ISSUE THREAD

**Issue by EraYaN** [Zeranoe/mingw-w64-build#8]
This bug: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=81797

Stops the standard library from building on on macOS on a APFS volume sometimes.

Moving to 7.4.0 apparently fixes that. So when that releases, moving to that might be worth it. 8.1.0 also fixes the issue, but that might be too big of a jump.

**Comment by Zeranoe** [comment]
The script uses GCC's 8 SVN branch, so this change should be included in that.
